exports.ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST'
exports.ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS'
exports.ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL'

exports.ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
exports.ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
exports.ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

exports.NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST'
exports.NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
exports.NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET'
exports.NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL'

exports.DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
exports.DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
exports.DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET'
exports.DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

exports.UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
exports.UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
exports.UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET'
exports.UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'

exports.PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
exports.PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
exports.PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

exports.NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
exports.NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
exports.NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
exports.NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

exports.GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
exports.GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
exports.GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

exports.DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
exports.DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
exports.DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
exports.DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

exports.CLEAR_ERRORS = 'CLEAR_ERRORS'