exports.ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST' 
exports.ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
exports.ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

exports.PRODUCTS_DETAIL_FAIL = 'PRODUCTS_DETAIL_FAIL'
exports.PRODUCTS_DETAIL_SUCCESS = 'PRODUCTS_DETAIL_SUCCESS'
exports.PRODUCTS_DETAIL_REQUEST = 'PRODUCTS_DETAIL_REQUEST'


exports.CLEAR_ERRORS = 'CLEAR_ERRORS'